{% set name = "nelson-core" %}
{% set version = "0.3.0" %}
{% set sha256 = "d9212109b54c677423ff1e3998c30d3dd9f165734b8fc40cc279dce961e0edd2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Nelson-numerical-software/nelson-minimalist-core/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja  # [unix or win]
    - pkgconfig  # [osx or win]
  host:
    - eigen

test:
  commands:
    - test -d ${PREFIX}/include/nelson  # [unix]
    - test -f ${PREFIX}/include/nelson/core/EvaluateCommand.hpp  # [unix]
    - if exist %LIBRARY_PREFIX%\include\nelson\core\EvaluateCommand.hpp (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/Nelson-numerical-software/nelson-minimalist-core
  summary: 'Minimalistic core of Nelson, a numerical interpreter'
  license: LGPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://nelson-numerical-software.github.io/nelson-website/help/en_US/
  dev_url: https://github.com/Nelson-numerical-software/nelson-minimalist-core

extra:
  recipe-maintainers:
    - Hind-M
    - JohanMabille
    - Nelson-numerical-software
